### PR TITLE
fixes 89: add term option to SSHClientInteraction and use to call invoke shell

### PR DESCRIPTION
**Pull request by sar772004**
fixes 89: add term option to SSHClientInteraction and use to call invoke shell

### CODE REVIEW

**Comment by sar772004** [comment]
Can the maintainer pls review and merge this, simple change and tests are all passed.

**Comment by sar772004** [comment]
@fruch for notification, please check and merge this change. Thanks

**Review by fruch — APPROVED** [review]
LGTM

**Comment by sar772004** [comment]
Thanks @fruch , it seems the deploy of new version is skipped, can you pls take a look ?

**Comment by fruch** [comment]
> Thanks @fruch , it seems the deploy of new version is skipped, can you pls take a look ?

I've now released v0.3.5

**Pull request merged**
