### PR TITLE
Python3 support for tail()

### PR DESCRIPTION
**Pull request by monkut**

### CODE REVIEW

**Comment by monkut** [comment]
Various updates in an attempt to support python3 with tail().

**Comment by fgimian** [comment]
Really appreciate the effort on this, I will check it out soon.  I may need to refactor it a little to improve a few minor aspects.

Thanks
Fotis

**Comment by monkut** [comment]
No, problem! Thought the maxint replacement alone would initially resolve the issue, but hit some other bytes/str issues after that.

**Comment by fruch** [comment]
closing fixing it in #24

**Pull request closed without merging**
